# Generated by Django 4.1.7 on 2023-10-30 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("Name", models.CharField(max_length=30)),
                (
                    "Phone",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("Password", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="Todolist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("desc", models.CharField(max_length=80)),
                ("duedate", models.DateField()),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
