# Generated by Django 4.1.7 on 2023-10-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolist",
            name="status",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
